### ISSUE TITLE
Create a New ToDo Activity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#1]
Create a new activity to take input from user for a new task.
The fields are : -
1. Task Name (EditText)
2. Description (EditTExt)
3. Deadline (For now, an edit text string in form dd/mm/yyyy)
4. Enable Notification (Just a radio button)
5. Priority (An integer value from 1-5)
and Submit button.
Just make the layout of the activity with these fields, don't worry about database and intents for now.

**Comment by shiv07tiwari** [comment]
@opencodebot help

**Comment by chanmol1999** [comment]
Is this the only pinned issue
it has been already assigned

**Comment by shiv07tiwari** [comment]
@chanmol1999 yes right now you can pick this one. @VidhiSah is working on something else.  As this is a pinned issue, i suggest you to solve this one as soon as possible. 😁

**Comment by achintagrawal** [comment]
@opencodebot claim

**Comment by achintagrawal** [comment]
sir i also want to do it

**Comment by shiv07tiwari** [comment]
@achintagrawal We already have a PR for this one. You can go for https://github.com/opencodeiiita/ToDo-List-App/issues/12.
It is a similar task !

**Comment by achintagrawal** [comment]
@shiv07tiwari  okk sir

**Comment by akshaykalola28** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
@akshaykalola28 This issue is already claimed.
@chanmol1999  Please solve this one as soon as possible so that we can move forward.
