### ISSUE TITLE
Change the Floating Action Button Icon

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#16]
Change the icon of FAB to something relevant, such as a + sign !

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by akshaykalola28** [comment]
@opencodebot claim

**Comment by DreamyPhobic** [comment]
@akshaykalola28 It's been 4 days, there are no updates on this, so I am unassigning it. If you still want to work on this claim it again.

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by achintagrawal** [comment]
@opencodebot  claim

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by vaibhav-1207** [comment]
@opencodebot  claim
