### ISSUE TITLE
Add Recycler View in home screen

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#18]
1. Make a array list of approx 10 items.
2. Implement arraylist in home screen.
3. Load the arraylist with dummy array list you made.
PS : we'll use this array list (with modifications) to display our to-do list !!

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by BinduVerma123** [comment]
@shiv07tiwari what elements have to be added in that array?

**Comment by BinduVerma123** [comment]
@shiv07tiwari sir..i am having a problem with adjusting the proxy settings while setting up this project in the android studio in my pc....plz help me out!!

**Comment by shiv07tiwari** [comment]
@BinduVerma123  Send me the error message in slack/zulip. I'll see the issue.
