### ISSUE TITLE
Add reviewers to the repo

### ISSUE THREAD

**Issue by DreamyPhobic** [opencodeiiita/ToDo-List-App#20]
Create a file named reviewers.yml in .github folder and add @DreamyPhobic and @shiv07tiwari as reviewers. See other repos of our org for reference.

**Comment by ashish4321** [comment]
@opencodebot claim

**Comment by ashish4321** [comment]
@DreamyPhobic can i work on it?

**Comment by DreamyPhobic** [comment]
@ashish4321 again claim it.

**Comment by ashish4321** [comment]
@opencodebot claim
