### ISSUE TITLE
Rename "todo" to NewToDoActivity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#25]
Just rename the todo activity to "NewToDoActivity"

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
@Archies11 please follow these instructions and complete them asap.

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
@Archies11 please solve your existing couple of issues before claiming this one.

**Comment by harchani-ritik** [comment]
@opencodebot claim

**Comment by harchani-ritik** [comment]
@opencodebot claim
