### ISSUE TITLE
Remove the text from the HomeScreen.

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#3]
We have a text in HomeScreen in centre. Remove that text from the screen.

**Comment by VidhiSah** [comment]
@opencodebot claim

**Comment by chanmol1999** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
@chanmol1999 This issue is already claimed by @VidhiSah .
You can work on some other issue. 😄

**Comment by shiv07tiwari** [comment]
@chanmol1999 Maybe you can work on the pinned issue if you like. Its an easy one.
Feel free to contact regarding any doubts.

**Comment by DreamyPhobic** [comment]
@VidhiSah If you are still working on this issue, comment ```@opencodebot claim``` again, you will get an invitation link. After accepting the invitation, you have to again claim this issue by commenting ```@opencodebot claim```, bot will add you as an assignee.

**Comment by DreamyPhobic** [comment]
@opencodebot unclaim

**Comment by VidhiSah** [comment]
@opencodebot claim

**Comment by VidhiSah** [comment]
@opencodebot claim

**Comment by DreamyPhobic** [comment]
@VidhiSah It's been 4 days, there are no updates on this, so I am unassigning it. If you still want to work on this claim it again.

**Comment by chanmol1999** [comment]
@opencodebot claim

**Comment by DreamyPhobic** [comment]
@chanmol1999 I have updated the issue, no longer we need that text on HomeScreen, so remove it.

**Comment by harchani-ritik** [comment]
@opencodebot claim

**Comment by harchani-ritik** [comment]
@DreamyPhobic Can I have the issue?
