### ISSUE TITLE
update the name of new todo in mainactivity.java in the calling intent

### ISSUE THREAD

**Issue by chanmol1999** [opencodeiiita/ToDo-List-App#34]
> Please provide us with the following information:
> ---------------------------------------------------------------
Instead of todo.class it should be the updated name of activity
### This issue is for a: (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by chanmol1999** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
I did this because it was hindering the other issues.
