### ISSUE TITLE
Add a DatePicker in NewToDoActivity. 

### ISSUE THREAD

**Issue by DreamyPhobic** [opencodeiiita/ToDo-List-App#38]
### This issue is for a:
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression

Replace the date EditText with a DatePicker. The current date should be selected by default.

**Comment by BinduVerma123** [comment]
@opencodebot claim

**Comment by BinduVerma123** [comment]
@opencodebot claim
