### ISSUE TITLE
Add colours to Resource xml File

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#4]
Add atleast 30 colour resources to the colour resource xml file.

**Comment by achintagrawal** [comment]
@opencodebot claim

**Comment by shiv07tiwari** [comment]
@achintagrawal you can solve this.

**Comment by DreamyPhobic** [comment]
@achintagrawal If you are still working on this issue, claim it again now bot is working, you will get an invitation link. After accepting the invitation, you have to again claim this issue, bot will add you as an assignee.

**Comment by Kartik2301** [comment]
shiv07tiwari Sir , if the task is currently assigned , i want to take up this issue

**Comment by shiv07tiwari** [comment]
@Kartik2301, achint is already working on this.
@achintagrawal please follow @DreamyPhobic 's instructions ASAP.

**Comment by harchani-ritik** [comment]
@opencodebot claim

**Comment by DreamyPhobic** [comment]
#31 closes this.
