### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by BinduVerma123** [opencodeiiita/ToDo-List-App#48]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by harchani-ritik** [comment]
@opencodebot claim

**Comment by harchani-ritik** [comment]
@DreamyPhobic  Request to add a suitable label to this issue.
