### ISSUE TITLE
Data is lost on screen rotation in New ToDo Activity

### ISSUE THREAD

**Issue by shiv07tiwari** [opencodeiiita/ToDo-List-App#59]
### This issue is for a: (mark with an `x`)
- [x] bug report -> please search issues before submitting

### Minimal steps to reproduce
> Enter some details in new todo, rotate the screen, data is lost.
### Expected/desired behavior
>Data should not disappear.
### Mention any other details that might be useful
Use onSavedInstanceState

**Comment by harchani-ritik** [comment]
@opencodebot claim
